name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: |
          cd 04/05.continuous-testing
          npm install

      - name: Check Redis
        run: redis-cli -h 127.0.0.1 -p 6379 ping

      - name: Run tests
        run: |
          cd 04/05.continuous-testing
          npm test